name: 💡 Идея
description: Чего не хватает в Grimsby
labels: [идея]
body:
  - type: textarea
    id: idea
    attributes:
      label: Что хотелось бы
      description: Опишите идею и зачем она вам — так проще понять, как её лучше сделать.
    validations:
      required: true
